// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OficinaCardozo.Infrastructure.Data;

#nullable disable

namespace OficinaCardozo.Infrastructure.Migrations
{
    [DbContext(typeof(OficinaDbContext))]
    [Migration("20251011145222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF_CNPJ");

                    b.Property<string>("EmailPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL_PRINCIPAL");

                    b.Property<string>("EnderecoPrincipal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("ENDERECO_PRINCIPAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("TELEFONE_PRINCIPAL");

                    b.HasKey("Id");

                    b.ToTable("OFICINA_CLIENTE");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("DataOrcamento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_ORCAMENTO");

                    b.Property<int>("IdOrdemServico")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ORDEM_SERVICO");

                    b.Property<int>("IdStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdemServico");

                    b.HasIndex("IdStatus");

                    b.ToTable("OFICINA_ORCAMENTO");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrcamentoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("OFICINA_ORCAMENTO_STATUS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Criado"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pendente aprovacao"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Aprovado"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Rejeitado"
                        });
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long?>("DataEntrega")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_ENTREGA");

                    b.Property<long?>("DataFinalizacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_FINALIZACAO");

                    b.Property<long>("DataSolicitacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_SOLICITACAO");

                    b.Property<int>("IdStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_STATUS");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_VEICULO");

                    b.HasKey("Id");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("OFICINA_ORDEM_SERVICO");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServicoPeca", b =>
                {
                    b.Property<int>("IdOrdemServico")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ORDEM_SERVICO");

                    b.Property<int>("IdPeca")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PECA")
                        .HasColumnOrder(1);

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALOR_UNITARIO");

                    b.HasKey("IdOrdemServico", "IdPeca");

                    b.HasIndex("IdPeca");

                    b.ToTable("OFICINA_ORDEM_SERVICO_PECA");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServicoServico", b =>
                {
                    b.Property<int>("IdOrdemServico")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ORDEM_SERVICO");

                    b.Property<int>("IdServico")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_SERVICO");

                    b.Property<decimal?>("ValorAplicado")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALOR_APLICADO");

                    b.HasKey("IdOrdemServico", "IdServico");

                    b.HasIndex("IdServico");

                    b.ToTable("OFICINA_ORDEM_SERVICO_SERVICO");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServicoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("OFICINA_ORDEM_SERVICO_STATUS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Recebida"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Em diagnostico"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Em elaboracao"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Aguardando aprovacao"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Em execucao"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Finalizada"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Entregue"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Cancelada"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Devolvida"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Orçamento elaborado"
                        });
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoIdentificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CODIGO_IDENTIFICADOR");

                    b.Property<string>("LocalizacaoEstoque")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("LOCALIZACAO_ESTOQUE");

                    b.Property<string>("NomePeca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME_PECA");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("OBSERVACOES");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRECO");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QTD_ESTOQUE");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QTD_MINIMA");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.HasKey("Id");

                    b.ToTable("OFICINA_PECA");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("DescricaoDetalhadaServico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO_DETALHADA_SERVICO");

                    b.Property<string>("FrequenciaRecomendada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("FREQUENCIA_RECOMENDADA");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME_SERVICO");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRECO");

                    b.Property<int>("TempoEstimadoExecucao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TEMPO_ESTIMADO_EXECUCAO");

                    b.HasKey("Id");

                    b.ToTable("OFICINA_SERVICO");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Complexidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("COMPLEXIDADE");

                    b.Property<long>("DataCriacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("HASH_SENHA");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME_USUARIO");

                    b.HasKey("Id");

                    b.ToTable("OFICINA_USUARIO");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ANO_FABRICACAO");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("COR");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("MARCA_MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLACA");

                    b.Property<string>("TipoCombustivel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("TIPO_COMBUSTIVEL");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("OFICINA_VEICULO");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Orcamento", b =>
                {
                    b.HasOne("OficinaCardozo.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("Orcamentos")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficinaCardozo.Domain.Entities.OrcamentoStatus", "Status")
                        .WithMany("Orcamentos")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("OficinaCardozo.Domain.Entities.OrdemServicoStatus", "Status")
                        .WithMany("OrdensServico")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficinaCardozo.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("OrdensServico")
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServicoPeca", b =>
                {
                    b.HasOne("OficinaCardozo.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("OrdemServicoPecas")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficinaCardozo.Domain.Entities.Peca", "Peca")
                        .WithMany("OrdensServicoPecas")
                        .HasForeignKey("IdPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServicoServico", b =>
                {
                    b.HasOne("OficinaCardozo.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("OrdemServicoServicos")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficinaCardozo.Domain.Entities.Servico", "Servico")
                        .WithMany("OrdensServicoServicos")
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("OficinaCardozo.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrcamentoStatus", b =>
                {
                    b.Navigation("Orcamentos");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("Orcamentos");

                    b.Navigation("OrdemServicoPecas");

                    b.Navigation("OrdemServicoServicos");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.OrdemServicoStatus", b =>
                {
                    b.Navigation("OrdensServico");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Peca", b =>
                {
                    b.Navigation("OrdensServicoPecas");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Servico", b =>
                {
                    b.Navigation("OrdensServicoServicos");
                });

            modelBuilder.Entity("OficinaCardozo.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("OrdensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
